name: CI Pipeline

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover app

